### ISSUE TITLE
Doubt about the catalog

### ISSUE THREAD

**Issue by alverad-katsuro** [okd-project/okderators-catalog-index#7]
Hello, I installed a vanilla kubernetes (k8s) and for management I installed the openshift console and I like to add graphs to my catalog in openshift console, can this project help me?

Operator Store

![image](https://github.com/user-attachments/assets/2c3e6b4a-2264-40b3-98cb-7fd362b3e4ff)

Develop View
![image](https://github.com/user-attachments/assets/310ca71d-8173-43ce-93af-cd5d9f1fd1fe)

If this is not the intention, do you have a guide on how to add charts to the openshift console?

**Comment by SupremeMortal** [comment]
This project's catalog is targeted at [OKD](https://okd.io) based clusters, so it's likely your vanilla cluster could run into issues which is not within the scope of this project to fix.

**Comment by alverad-katsuro** [comment]
Thank you for your time!! O/
